import type { Lesson } from "./courseTypes";

export const b1B2Lessons: Lesson[] = [
  {
    id: "b1-past-narration",
    level: "B1",
    unit: "Past narration",
    title: "Passé composé or imparfait?",
    summary: "Choose between completed events and background, habits, or actions already in progress.",
    objective: "Narrate a past scene by separating foregrounded events from background circumstances.",
    rule: "Use the passé composé to present an event as completed or bounded. Use the imparfait for description, habitual action, background circumstances, or an action in progress. The choice concerns viewpoint, not simply how long the action lasted.",
    pattern: "background or ongoing action (imparfait) + completed event (passé composé)",
    examples: [
      {
        fr: "Pendant que je préparais le dîner, Paul a téléphoné.",
        en: "While I was preparing dinner, Paul called.",
      },
      {
        fr: "Chaque été, nous passions deux semaines chez nos grands-parents.",
        en: "Every summer, we used to spend two weeks at our grandparents’ home.",
      },
    ],
    trap: "A long action is not automatically in the imparfait: « J’ai travaillé pendant deux heures » is bounded and completed.",
    exercise: {
      prompt: "Quand j’étais petit, je ___ au parc tous les dimanches.",
      options: ["suis allé", "allais", "irai"],
      answer: "allais",
      rationale: "« Tous les dimanches » describes a repeated past habit, so the imparfait is required.",
    },
    prerequisites: ["a2-03"],
    tags: ["past", "aspect", "passé composé", "imparfait", "narration"],
    sourceKeys: ["fei", "tv5"],
    sourceNote: "FEI-style inventory guidance supports B1 consolidation; the aspect contrast and examples were checked against mainstream learner usage rather than treated as a duration rule.",
  },
  {
    id: "b1-plus-que-parfait",
    level: "B1",
    unit: "Past narration",
    title: "The plus-que-parfait",
    summary: "Place one past event before another past reference point.",
    objective: "Show clearly that one completed event happened before another past event or state.",
    rule: "Form the plus-que-parfait with avoir or être in the imparfait plus a past participle. Use it when an action was already complete before another past event, state, or moment.",
    pattern: "imparfait of avoir/être + past participle",
    examples: [
      { fr: "Elle était déjà partie quand je suis arrivé.", en: "She had already left when I arrived." },
      {
        fr: "Nous avons retrouvé le café où nous avions déjeuné.",
        en: "We found the café where we had eaten lunch.",
      },
    ],
    trap: "The plus-que-parfait does not simply mean ‘a long time ago’; it expresses a relationship between two past points.",
    exercise: {
      prompt: "Choose the tense that explicitly marks anteriority: « À midi, il a constaté qu’il ___ la porte ouverte en partant à huit heures. »",
      options: ["avait laissé", "laissait", "a laissé"],
      answer: "avait laissé",
      rationale: "Leaving the door open was already complete before the noon discovery, so the plus-que-parfait explicitly marks the earlier past event.",
    },
    prerequisites: ["b1-past-narration"],
    tags: ["past", "plus-que-parfait", "sequence", "compound tense"],
    sourceKeys: ["fei", "eduscol", "tv5"],
    sourceNote: "Level placement follows inventory guidance; formation and temporal anteriority use standard French grammatical terminology.",
  },
  {
    id: "b1-futur-simple",
    level: "B1",
    unit: "Future and hypothesis",
    title: "The futur simple",
    summary: "Express future events, predictions, promises, and future sequences.",
    objective: "Form the futur simple and use it in both main clauses and future time clauses.",
    rule: "Add -ai, -as, -a, -ons, -ez, -ont to a future stem: normally the full infinitive for regular -er and -ir verbs, the infinitive without its final -e for regular -re verbs (vendre → vendr-), or an irregular future stem. In a future time clause introduced by quand, lorsque, or dès que, French normally uses a future tense even where English uses a present form.",
    pattern: "future stem (regular -er/-ir infinitive; regular -re minus final -e) + -ai, -as, -a, -ons, -ez, -ont",
    examples: [
      { fr: "Quand tu arriveras, nous dînerons.", en: "When you arrive, we will have dinner." },
      { fr: "Il fera probablement froid demain.", en: "It will probably be cold tomorrow." },
    ],
    trap: "After conditional si, use the present rather than the future: « Si tu viens, nous sortirons », not « si tu viendras ».",
    exercise: {
      prompt: "Quand elle ___, elle nous appellera.",
      options: ["arrivera", "arrive", "arriverait"],
      answer: "arrivera",
      rationale: "The clause introduced by « quand » refers to a future event, so standard French uses the futur simple.",
    },
    prerequisites: ["a2-04"],
    tags: ["future", "futur simple", "time clause", "prediction"],
    sourceKeys: ["fei", "academie", "oqlf"],
    sourceNote: "The regular -re stem rule and future-time-clause contrast follow standard formation guidance; si-clauses are explicitly distinguished.",
  },
  {
    id: "b1-conditionnel-present",
    level: "B1",
    unit: "Future and hypothesis",
    title: "The conditionnel présent",
    summary: "Express hypothetical results, polite requests, advice, and softened claims.",
    objective: "Build hypothetical present or future conditions with si + imparfait while distinguishing open conditions with si + present.",
    rule: "Form the present conditional with the future stem and the imparfait endings. For a present or future condition presented as hypothetical, unlikely, or contrary to fact, use si + imparfait and a conditionnel présent result. For an open condition, use si + present with a present, future, or imperative result.",
    pattern: "si + imparfait → conditionnel présent",
    examples: [
      {
        fr: "Si j’avais plus de temps, je voyagerais davantage.",
        en: "If I had more time, I would travel more.",
      },
      {
        fr: "Pourriez-vous fermer la fenêtre, s’il vous plaît ?",
        en: "Could you close the window, please?",
      },
    ],
    trap: "Do not put the conditional directly after hypothetical si: say « si j’avais », not « si j’aurais ».",
    exercise: {
      prompt: "Nous habitons loin de la mer. Si nous habitions près de la mer, nous y ___ chaque week-end.",
      options: ["irons", "irions", "allions"],
      answer: "irions",
      rationale: "The opening sentence establishes a present reality; the si-clause imagines its opposite, so the hypothetical result takes the present conditional.",
    },
    prerequisites: ["b1-futur-simple", "a2-02", "a2-12"],
    tags: ["conditionnel présent", "hypothesis", "si clause", "politeness"],
    sourceKeys: ["fei", "eduscol", "oqlf"],
    sourceNote: "The lesson distinguishes an open si + present condition from the hypothetical si + imparfait pattern and retains the present conditional’s common polite use.",
  },
  {
    id: "b1-subjonctif-present",
    level: "B1",
    unit: "Mood and stance",
    title: "Essential uses of the present subjunctive",
    summary: "Express necessity, wishes, emotion, judgment, or doubt in a dependent clause.",
    objective: "Recognize common subjunctive triggers and choose between an infinitive and que + subjunctive.",
    rule: "Many expressions of necessity, will, emotion, judgment, and doubt require que + subjunctive. When the subject of both actions is the same, French often uses an infinitive instead of que + subjunctive.",
    pattern: "trigger + que + new subject + subjunctive; same subject → infinitive",
    examples: [
      { fr: "Il faut que vous fassiez attention.", en: "You need to be careful." },
      { fr: "Je préfère partir tôt.", en: "I prefer to leave early." },
    ],
    trap: "Que alone does not trigger the subjunctive. An affirmative assertion such as « Je pense qu’il a raison » normally takes the indicative.",
    exercise: {
      prompt: "Je veux que tu ___ avec nous.",
      options: ["viens", "viennes", "viendras"],
      answer: "viennes",
      rationale: "The two clauses have different subjects, and « vouloir que » requires the subjunctive.",
    },
    prerequisites: ["a2-11"],
    tags: ["subjunctive", "mood", "necessity", "desire", "same subject"],
    sourceKeys: ["fei", "academie"],
    sourceNote: "Only high-frequency B1 triggers are taught here; the note avoids presenting que itself as a trigger.",
  },
  {
    id: "b1-object-pronouns-y-en",
    level: "B1",
    unit: "Pronouns and cohesion",
    title: "Object pronouns, y, and en",
    summary: "Replace repeated complements and place several pronouns in a fixed sequence.",
    objective: "Replace two complements accurately with pre-verbal object pronouns.",
    rule: "Before a conjugated verb, the normal order is me/te/se/nous/vous + le/la/les + lui/leur + y + en. Y generally replaces a place or à + thing; en generally replaces de + a noun phrase or an indefinite or quantified noun phrase and can refer to things or people.",
    pattern: "me/te/se/nous/vous → le/la/les → lui/leur → y → en → verb",
    examples: [
      { fr: "Je donne les clés à Léa. → Je les lui donne.", en: "I give the keys to Léa. → I give them to her." },
      { fr: "Tu veux des pommes ? → Oui, j’en prends deux.", en: "Do you want some apples? → Yes, I’ll take two." },
    ],
    trap: "In careful French, y normally does not replace à + a person: say « Je pense à elle ». En can correctly represent people, especially an indefinite or quantified reference: « Des collègues, j’en connais plusieurs. » For an identified or emphasized person, de lui or d’elle is often preferred. Affirmative imperatives also use a different order.",
    exercise: {
      prompt: "Replace both complements in « Elle parle de son projet à ses collègues. »",
      options: ["Elle en leur parle.", "Elle leur en parle.", "Elle les y parle."],
      answer: "Elle leur en parle.",
      rationale: "« À ses collègues » becomes leur and « de son projet » becomes en; leur precedes en.",
    },
    prerequisites: ["a2-05", "a2-06"],
    tags: ["pronouns", "direct object", "indirect object", "y", "en", "word order"],
    sourceKeys: ["fei", "eduscol", "oqlf"],
    sourceNote: "The fixed pre-verbal sequence is taught in standard form; the lesson distinguishes the restriction on y from the accepted use of en for people and flags affirmative-imperative ordering as a separate case.",
  },
  {
    id: "b1-relative-pronouns",
    level: "B1",
    unit: "Pronouns and cohesion",
    title: "Relative pronouns: qui, que, où, dont, and ce forms",
    summary: "Connect clauses while showing the missing element’s grammatical role.",
    objective: "Select a relative pronoun from its role inside the relative clause.",
    rule: "Use qui for a subject, que for a direct object, où for a place or time, and dont for a complement linked directly by de to a governing verb, adjective, or noun. When there is no stated antecedent, use ce qui, ce que, or ce dont. If de belongs to a larger prepositional group, dont is not used; a later lesson covers the duquel family.",
    pattern: "antecedent + relative pronoun + clause; no antecedent → ce qui/ce que/ce dont",
    examples: [
      {
        fr: "Le livre que je lis est celui dont tu m’as parlé.",
        en: "The book I am reading is the one you told me about.",
      },
      {
        fr: "Je comprends ce que tu veux, mais pas ce qui t’inquiète.",
        en: "I understand what you want, but not what is worrying you.",
      },
    ],
    trap: "Choose the pronoun from its function inside the relative clause, not from the noun immediately before it.",
    exercise: {
      prompt: "Voici le document ___ j’ai besoin.",
      options: ["que", "qui", "dont"],
      answer: "dont",
      rationale: "The expression is « avoir besoin de quelque chose », so de + document becomes dont.",
    },
    prerequisites: ["a2-07"],
    tags: ["relative pronouns", "qui", "que", "où", "dont", "cohesion"],
    sourceKeys: ["fei", "eduscol", "oqlf"],
    sourceNote: "The lesson consolidates the high-frequency relative system and makes syntactic function, not proximity, the selection rule.",
  },
  {
    id: "b1-past-participle-agreement",
    level: "B1",
    unit: "Agreement and compression",
    title: "Core past-participle agreement",
    summary: "Apply the central agreement rules with non-pronominal être verbs and with avoir.",
    objective: "Make past participles agree with a non-pronominal être-subject or, normally, a preceding direct object with avoir.",
    rule: "With a non-pronominal verb conjugated with être, the past participle agrees with the subject. With avoir, it normally agrees with a direct object only when that object appears before the participle. Later lessons cover pronominal verbs and exceptions such as en, fait + infinitive, and laissé + infinitive.",
    pattern: "non-pronominal être → subject agreement; avoir → normally agree with a preceding direct object",
    examples: [
      { fr: "Elles sont arrivées à neuf heures.", en: "They arrived at nine o’clock." },
      { fr: "Les photos que j’ai prises sont nettes.", en: "The photos I took are sharp." },
    ],
    trap: "A preceding indirect object causes no agreement: « les personnes à qui j’ai parlé », because parler takes à.",
    exercise: {
      prompt: "Les lettres que Marie a ___ hier sont sur la table.",
      options: ["écrit", "écrite", "écrites"],
      answer: "écrites",
      rationale: "Que represents the feminine plural direct object « les lettres » and precedes the participle.",
    },
    prerequisites: ["a2-01", "b1-relative-pronouns"],
    tags: ["agreement", "past participle", "être", "avoir", "direct object"],
    sourceKeys: ["fei", "academie", "oqlf"],
    sourceNote: "The core metropolitan standard is taught; OQLF was used only to confirm the same detailed agreement logic, not a Québec-specific variant.",
  },
  {
    id: "b1-gerondif-participe-present",
    level: "B1",
    unit: "Agreement and compression",
    title: "The gérondif and present participle",
    summary: "Condense actions that express time, manner, means, or circumstance.",
    objective: "Use en + present participle without creating an unintended subject.",
    rule: "The gérondif is en + present participle and normally shares its implied subject with the main verb. A bare present participle can modify a noun or introduce a circumstance and is invariable. Do not confuse it with a participial adjective, which expresses a quality or state and agrees with its noun: « des personnes convaincantes », but « des personnes convainquant le jury ».",
    pattern: "en + present participle; normally the same subject as the main clause",
    examples: [
      { fr: "En traversant la rue, Paul a aperçu Léa.", en: "While crossing the street, Paul caught sight of Léa." },
      {
        fr: "Les personnes habitant ici connaissent bien le quartier.",
        en: "The people living here know the neighborhood well.",
      },
    ],
    trap: "Avoid a dangling gérondif: in « En sortant, la pluie a commencé », the grammar incorrectly makes the rain the one leaving.",
    exercise: {
      prompt: "En ___ régulièrement, elle a gagné en confiance.",
      options: ["pratiqué", "pratiquant", "pratique"],
      answer: "pratiquant",
      rationale: "The gérondif is formed with en followed by the present participle.",
    },
    prerequisites: ["a1-03", "a1-04"],
    tags: ["gérondif", "present participle", "participial adjective", "same subject", "clause reduction"],
    sourceKeys: ["fei", "eduscol", "oqlf"],
    sourceNote: "The lesson teaches the same-subject constraint that prevents dangling modifiers and distinguishes the invariable present participle from the agreeing participial adjective.",
  },
  {
    id: "b1-passive-and-on",
    level: "B1",
    unit: "Voice and reporting",
    title: "The passive voice and active on",
    summary: "Shift attention from the agent to the receiver of an action.",
    objective: "Form a passive sentence and recognize when everyday French prefers active on.",
    rule: "Form the passive with être in the required tense plus a past participle agreeing with the subject. The agent, when expressed, is usually introduced by par. Everyday French often prefers an active sentence with on.",
    pattern: "receiver + être in the required tense + agreeing past participle (+ par + agent)",
    examples: [
      { fr: "Le musée a été rénové par la ville.", en: "The museum was renovated by the city." },
      { fr: "On vend du pain frais ici.", en: "Fresh bread is sold here." },
    ],
    trap: "Only a verb with a direct object can normally form a passive; an intransitive verb such as arriver cannot.",
    exercise: {
      prompt: "Ces règles ___ par tous les participants.",
      options: ["respectent", "sont respectées", "ont respecté"],
      answer: "sont respectées",
      rationale: "The receiver « ces règles » is the passive subject, and the participle agrees in the feminine plural.",
    },
    prerequisites: ["b1-past-participle-agreement"],
    tags: ["passive voice", "on", "agent", "agreement", "register"],
    sourceKeys: ["fei", "eduscol"],
    sourceNote: "The structural passive is paired with active on to reflect both formal grammar and common contemporary usage.",
  },
  {
    id: "b1-indirect-speech-questions",
    level: "B1",
    unit: "Voice and reporting",
    title: "Basic reported speech and indirect questions",
    summary: "Report statements and questions without copying their original sentence structure.",
    objective: "Report a statement, yes/no question, or information question with standard embedded word order.",
    rule: "Introduce a reported statement with que, a yes/no question with si, and an information question with its question word. An indirect question uses ordinary subject–verb order and drops est-ce que and pronoun inversion. Qu’est-ce qui becomes ce qui; qu’est-ce que or direct interrogative que becomes ce que.",
    pattern: "statement → que; yes/no question → si; information question → question word + subject + verb; qu’est-ce qui → ce qui; qu’est-ce que/que → ce que",
    examples: [
      { fr: "Paul dit qu’il viendra demain.", en: "Paul says that he will come tomorrow." },
      { fr: "« Où habites-tu ? » → Elle demande où tu habites.", en: "‘Where do you live?’ → She asks where you live." },
    ],
    trap: "Do not retain both markers: « Il demande où est-ce que tu habites » is nonstandard in careful French.",
    exercise: {
      prompt: "Report « Est-ce qu’elle vient ? » after « Il demande… »",
      options: ["Il demande qu’elle vient.", "Il demande si elle vient.", "Il demande est-ce qu’elle vient."],
      answer: "Il demande si elle vient.",
      rationale: "A reported yes/no question is introduced by si.",
    },
    prerequisites: ["a1-08", "a2-11"],
    tags: ["reported speech", "indirect question", "si", "word order"],
    sourceKeys: ["fei", "eduscol", "oqlf"],
    sourceNote: "The careful-standard embedded order is taught; colloquial retention of est-ce que is identified but not accepted in the check.",
  },
  {
    id: "b1-logical-connectors",
    level: "B1",
    unit: "Discourse links and complements",
    title: "Cause, consequence, purpose, and concession",
    summary: "Make relationships between ideas explicit rather than joining every clause with et or mais.",
    objective: "Choose a connector that expresses the intended logical relationship and governs the correct mood.",
    rule: "Use connectors according to meaning: parce que or puisque for cause; donc or c’est pourquoi for consequence; pour + infinitive when the subject stays the same; pour que + subjunctive when subjects differ; même si + indicative or bien que + subjunctive for concession.",
    pattern: "same-subject purpose → pour + infinitive; different-subject purpose → pour que + subjunctive",
    examples: [
      { fr: "Je ferme la fenêtre pour que le bébé puisse dormir.", en: "I am closing the window so that the baby can sleep." },
      {
        fr: "Bien qu’il soit fatigué, il continue parce que l’examen approche.",
        en: "Although he is tired, he carries on because the exam is approaching.",
      },
    ],
    trap: "Do not use the subjunctive after même si: say « même s’il est fatigué », not « même s’il soit fatigué ».",
    exercise: {
      prompt: "Elle chuchote pour que personne ne l’___.",
      options: ["entend", "entendra", "entende"],
      answer: "entende",
      rationale: "Pour que introduces a purpose clause and requires the subjunctive.",
    },
    prerequisites: ["b1-subjonctif-present"],
    tags: ["connectors", "cause", "consequence", "purpose", "concession"],
    sourceKeys: ["cei", "fei"],
    sourceNote: "The connector set supports CEFR-style B1 coherence outcomes; it is a curated teaching progression, not an official exhaustive CEFR grammar list.",
  },
  {
    id: "b1-complement-prepositions",
    level: "B1",
    unit: "Discourse links and complements",
    title: "Verbs, adjectives, and nouns followed by à or de",
    summary: "Learn a predicate together with the structure it governs.",
    objective: "Supply à, de, or no preposition after common French predicates.",
    rule: "French predicates select their own complement pattern: réussir à faire, décider de faire, aider quelqu’un à faire, être prêt à, and avoir besoin de. The correct preposition cannot reliably be translated from English.",
    pattern: "learn predicate + complement together: réussir à; décider de; attendre + direct object",
    examples: [
      { fr: "Elle hésite à accepter ce poste.", en: "She hesitates to accept this position." },
      { fr: "Nous avons besoin de vérifier les résultats.", en: "We need to check the results." },
    ],
    trap: "Do not insert an English-based preposition: French says « attendre quelqu’un » and « chercher ses clés », with no pour.",
    exercise: {
      prompt: "Il a réussi ___ convaincre le comité.",
      options: ["à", "de", "pour"],
      answer: "à",
      rationale: "The required construction is « réussir à + infinitif ».",
    },
    prerequisites: ["a1-14"],
    tags: ["prepositions", "verb complements", "à", "de", "infinitive"],
    sourceKeys: ["fei", "tv5"],
    sourceNote: "High-frequency complement patterns are prioritized; learners should record each predicate with its construction rather than translate an English preposition.",
  },
  {
    id: "b2-futur-anterieur",
    level: "B2",
    unit: "Advanced time and hypothesis",
    title: "The futur antérieur",
    summary: "Present a future action as already complete before another future point.",
    objective: "Show that an action will be complete before a future event or deadline.",
    rule: "Form the futur antérieur with avoir or être in the futur simple plus a past participle. It commonly marks completion before a future deadline or event; it can also express a conjecture about a completed past event: « Il aura oublié. »",
    pattern: "future of avoir/être + past participle",
    examples: [
      { fr: "Quand tu arriveras, j’aurai terminé le rapport.", en: "When you arrive, I will have finished the report." },
      { fr: "Demain, elle sera partie avant midi.", en: "By noon tomorrow, she will have left." },
      { fr: "Il n’est pas venu ; il aura oublié notre rendez-vous.", en: "He did not come; he must have forgotten our appointment." },
    ],
    trap: "This tense expresses future anteriority, not merely a very distant future.",
    exercise: {
      prompt: "Choose the tense that presents the sending as completed by Friday: « D’ici vendredi, nous ___ le dossier au client. »",
      options: ["envoyons", "aurons envoyé", "enverrions"],
      answer: "aurons envoyé",
      rationale: "The requested meaning presents the sending as already complete by the future deadline, so the futur antérieur is the best answer.",
    },
    prerequisites: ["b1-futur-simple", "b1-past-participle-agreement"],
    tags: ["future", "futur antérieur", "anteriority", "compound tense"],
    sourceKeys: ["fei", "eduscol", "oqlf"],
    sourceNote: "The primary teaching value is future anteriority; the inferential use is included as a secondary meaning without the misleading suggestion that it is restricted to formal contexts.",
  },
  {
    id: "b2-conditionnel-passe-hypotheses",
    level: "B2",
    unit: "Advanced time and hypothesis",
    title: "Conditional past and mixed hypotheses",
    summary: "Discuss unreal past outcomes and consequences that cross time periods.",
    objective: "Construct unreal past and mixed-time hypotheses without placing a conditional after condition-introducing si.",
    rule: "Form the past conditional with avoir or être in the present conditional plus a past participle. A standard unreal past pattern is si + plus-que-parfait followed by conditionnel passé. If the past condition has a present result, the main clause can instead use the present conditional.",
    pattern: "si + plus-que-parfait → conditionnel passé; past condition + present result → conditionnel présent",
    examples: [
      { fr: "Si tu m’avais prévenu, je serais venu.", en: "If you had warned me, I would have come." },
      {
        fr: "Si j’avais suivi ce conseil, je serais plus calme aujourd’hui.",
        en: "If I had followed that advice, I would be calmer today.",
      },
    ],
    trap: "Do not put the conditional in a si-clause that states a condition: use « si elle avait réservé », not « si elle aurait réservé ». This restriction does not apply when si means ‘whether’ in an indirect question (« Je me demande s’il viendrait »); elevated French may also use a conditional after concessive si.",
    exercise: {
      prompt: "Si elle avait réservé, nous ___ une table.",
      options: ["aurions eu", "avions eu", "ayons eu"],
      answer: "aurions eu",
      rationale: "An unreal past condition takes the plus-que-parfait, and its unreal past result takes the conditional past.",
    },
    prerequisites: ["b1-plus-que-parfait", "b1-conditionnel-present"],
    tags: ["conditional past", "counterfactual", "mixed hypothesis", "si clause"],
    sourceKeys: ["fei", "eduscol", "oqlf"],
    sourceNote: "The canonical counterfactual pattern is taught first; mixed-time results are added as a B2 extension governed by meaning.",
  },
  {
    id: "b2-subjonctif-passe",
    level: "B2",
    unit: "Mood and clause logic",
    title: "The past subjunctive",
    summary: "Place a completed dependent action before another reference point while retaining subjunctive meaning.",
    objective: "Form and use the modern past subjunctive after an appropriate trigger.",
    rule: "Form the past subjunctive with avoir or être in the present subjunctive plus a past participle. Use it when a subjunctive-triggering construction refers to an action viewed as already completed.",
    pattern: "present subjunctive of avoir/être + past participle",
    examples: [
      { fr: "Je suis ravie que vous soyez venus.", en: "I am delighted that you came." },
      { fr: "Il doute qu’elle ait compris la consigne.", en: "He doubts that she understood the instruction." },
    ],
    trap: "The normal modern past subjunctive is « ait fait » or « soit parti », not the literary imperfect subjunctive.",
    exercise: {
      prompt: "Je regrette qu’il ___ si tôt.",
      options: ["est parti", "soit parti", "partît"],
      answer: "soit parti",
      rationale: "Regret triggers the subjunctive, and the leaving was already completed, so the past subjunctive is needed.",
    },
    prerequisites: ["b1-subjonctif-present", "b1-past-participle-agreement"],
    tags: ["past subjunctive", "mood", "anteriority", "compound tense"],
    sourceKeys: ["fei", "academie"],
    sourceNote: "The course teaches the productive modern past subjunctive; literary imperfect-subjunctive forms are excluded from production.",
  },
  {
    id: "b2-indicative-vs-subjunctive",
    level: "B2",
    unit: "Mood and clause logic",
    title: "Choosing between indicative and subjunctive",
    summary: "Choose a mood according to assertion, stance, and the governing construction.",
    objective: "Explain a mood choice using both the governing expression and the speaker’s stance.",
    rule: "The indicative normally presents information as asserted or established. The subjunctive commonly presents it through desire, evaluation, emotion, possibility, or doubt. Polarity and speaker stance can alter the choice after verbs such as croire or penser.",
    pattern: "asserted proposition → usually indicative; nonasserted or evaluated proposition → often subjunctive",
    examples: [
      { fr: "Je sais qu’elle est prête.", en: "I know that she is ready." },
      { fr: "Je doute qu’elle soit prête.", en: "I doubt that she is ready." },
    ],
    trap: "Do not reduce the contrast to ‘certain versus uncertain.’ The governing expression matters: affirmative « penser que » normally takes the indicative, while its negative or interrogative form can take either mood according to stance.",
    exercise: {
      prompt: "Il est probable qu’il ___ demain.",
      options: ["viendra", "vienne", "viendrait"],
      answer: "viendra",
      rationale: "In standard usage, affirmative « il est probable que » normally asserts a likely fact and takes the indicative.",
    },
    prerequisites: ["b1-subjonctif-present", "b2-subjonctif-passe"],
    tags: ["indicative", "subjunctive", "mood", "stance", "assertion"],
    sourceKeys: ["fei", "academie"],
    sourceNote: "The rule is framed as construction plus stance, avoiding the inaccurate shortcut that every uncertain proposition requires the subjunctive.",
  },
  {
    id: "b2-conjunctions-ne-expletif",
    level: "B2",
    unit: "Mood and clause logic",
    title: "Mood after conjunctions and expletive ne",
    summary: "Control mood after temporal, concessive, purpose, and precautionary conjunctions.",
    objective: "Choose the correct mood after common conjunctions and interpret expletive ne as nonnegative.",
    rule: "Avant que, bien que, pour que, afin que, à condition que, and à moins que take the subjunctive. Après que takes the indicative because it presents the event as accomplished. A nonnegative ne may appear after avant que, à moins que, and expressions of fear or prevention.",
    pattern: "avant que + subjunctive; après que + indicative",
    examples: [
      { fr: "Pars avant qu’il ne soit trop tard.", en: "Leave before it is too late." },
      { fr: "Après qu’elle a signé, nous avons envoyé le contrat.", en: "After she signed, we sent the contract." },
    ],
    trap: "The ne in « avant qu’il ne soit » is optional and expletive; it does not mean ‘not.’ Conversely, standard « après que » takes an indicative tense.",
    exercise: {
      prompt: "Après qu’ils ___ leur décision, la séance a pris fin.",
      options: ["aient annoncé", "ont annoncé", "annoncent"],
      answer: "ont annoncé",
      rationale: "Après que introduces an accomplished event and therefore takes the indicative.",
    },
    prerequisites: ["b2-indicative-vs-subjunctive", "b1-logical-connectors"],
    tags: ["conjunctions", "subjunctive", "indicative", "après que", "expletive ne"],
    sourceKeys: ["academie", "oqlf"],
    sourceNote: "Normative standard usage was checked specifically for après que + indicative and for the optional, nonnegative ne after avant que, à moins que, and expressions of fear or prevention.",
  },
  {
    id: "b2-reported-speech-past",
    level: "B2",
    unit: "Reported viewpoint",
    title: "Past reported speech and tense shifts",
    summary: "Recalculate tense, pronouns, and time expressions from a past reporting viewpoint.",
    objective: "Report past statements by shifting tense and deictic expressions when the viewpoint requires it.",
    rule: "After a past reporting verb, a present commonly shifts to the imparfait, a passé composé to the plus-que-parfait, a future to the present conditional, and a future anterior to the past conditional. Deictic expressions may also shift: demain becomes le lendemain.",
    pattern: "present → imparfait; passé composé → plus-que-parfait; future → conditionnel présent",
    examples: [
      {
        fr: "« Je finirai demain. » → Elle a dit qu’elle finirait le lendemain.",
        en: "‘I will finish tomorrow.’ → She said that she would finish the next day.",
      },
      {
        fr: "« J’ai déjà envoyé le dossier. » → Il a expliqué qu’il avait déjà envoyé le dossier.",
        en: "‘I have already sent the file.’ → He explained that he had already sent the file.",
      },
    ],
    trap: "Tense shifting is not purely mechanical. A permanent truth or a fact the current speaker still explicitly asserts may retain its original tense.",
    exercise: {
      prompt: "One week later, report Monday’s statement « Nous partirons demain » after « Ils avaient annoncé… »",
      options: ["qu’ils partiraient le lendemain", "qu’ils partiront demain", "qu’ils partaient hier"],
      answer: "qu’ils partiraient le lendemain",
      rationale: "From the explicitly later reporting viewpoint, the original future becomes a future in the past and Monday’s « demain » becomes « le lendemain ».",
    },
    prerequisites: ["b1-indirect-speech-questions", "b1-plus-que-parfait", "b1-conditionnel-present"],
    tags: ["reported speech", "tense shift", "deixis", "sequence of tenses"],
    sourceKeys: ["fei", "eduscol"],
    sourceNote: "The standard backshift sequence is taught with an explicit caveat that current truths and viewpoint can license tense retention.",
  },
  {
    id: "b2-lequel-family",
    level: "B2",
    unit: "Advanced relatives",
    title: "The lequel family after prepositions",
    summary: "Build precise relative clauses after à, de, and other prepositions.",
    objective: "Choose and agree the correct lequel form after a preposition.",
    rule: "Lequel, laquelle, lesquels, and lesquelles agree with their antecedent. With à, lequel, lesquels, and lesquelles contract to auquel, auxquels, and auxquelles; à laquelle remains separate. With de, lequel, lesquels, and lesquelles contract to duquel, desquels, and desquelles; de laquelle remains separate. After a preposition and a person, preposition + qui is also often possible.",
    pattern: "preposition + lequel form; à + lequel → auquel and de + lequel → duquel; à laquelle/de laquelle stay separate",
    examples: [
      { fr: "C’est la décision à laquelle je pense.", en: "That is the decision I am thinking about." },
      { fr: "Voici les collègues avec lesquels je travaille.", en: "Here are the colleagues I work with." },
    ],
    trap: "Do not use lequel merely as a more formal replacement for direct-object que; its main relative use is after a preposition.",
    exercise: {
      prompt: "Quelles sont les raisons pour ___ vous refusez ?",
      options: ["lesquelles", "lesquels", "dont"],
      answer: "lesquelles",
      rationale: "The antecedent « raisons » is feminine plural and follows the preposition pour.",
    },
    prerequisites: ["b1-relative-pronouns"],
    tags: ["relative pronouns", "lequel", "prepositions", "agreement", "contractions"],
    sourceKeys: ["fei", "eduscol"],
    sourceNote: "The lesson distinguishes prepositional lequel forms from simple qui and que and includes the standard à/de contractions.",
  },
  {
    id: "b2-dont-duquel-ce-complements",
    level: "B2",
    unit: "Advanced relatives",
    title: "Dont, duquel, ce dont, and ce à quoi",
    summary: "Distinguish a simple de-complement from a larger prepositional expression.",
    objective: "Choose dont, a duquel form, or a ce + relative form from the complete complement structure.",
    rule: "Use dont when the antecedent is linked directly by de to a governing verb, adjective, or noun: parler de, être fier de, or le livre de l’auteur. Use the duquel family when de is embedded in a larger prepositional or nominal group, including compound prepositions ending in de, such as à côté de or près de, and phrases such as sur le site de. Without an antecedent, use ce dont for de and ce à quoi for à.",
    pattern: "direct de-complement → dont; de embedded in a larger group → duquel family",
    examples: [
      { fr: "Voilà ce dont j’ai besoin.", en: "That is what I need." },
      { fr: "La maison près de laquelle il habite est ancienne.", en: "The house near which he lives is old." },
    ],
    trap: "Dont cannot replace only the de embedded inside a larger group: use « à côté duquel », not « à côté dont ».",
    exercise: {
      prompt: "Le parc à côté ___ j’habite ferme à vingt heures.",
      options: ["dont", "duquel", "lequel"],
      answer: "duquel",
      rationale: "The complete preposition is « à côté de »; de + lequel contracts to duquel.",
    },
    prerequisites: ["b2-lequel-family"],
    tags: ["relative pronouns", "dont", "duquel", "ce dont", "ce à quoi"],
    sourceKeys: ["academie", "oqlf"],
    sourceNote: "The distinction was checked against detailed standard relative-pronoun descriptions; no regional-only form is taught.",
  },
  {
    id: "b2-pronominal-participle-agreement",
    level: "B2",
    unit: "Agreement and causation",
    title: "Agreement with pronominal verbs",
    summary: "Classify the pronominal use before applying either the direct-object test or subject agreement.",
    objective: "Distinguish reflexive or reciprocal object uses from pronominal uses in which se has no object function.",
    rule: "For reflexive or reciprocal uses of occasionally pronominal verbs, agreement follows the direct object. If se is the preceding direct object, the participle agrees with it and therefore with the subject. If se is indirect, it causes no agreement; a different preceding direct object can still trigger agreement. When se has no object function—notably with essentially pronominal verbs, passive pronominal uses, and some sense-changing pronominal uses—the participle normally agrees with the subject.",
    pattern: "reflexive/reciprocal use → direct-object test; se with no object function → normally subject agreement",
    examples: [
      { fr: "Elles se sont lavées.", en: "They washed themselves." },
      { fr: "Elles se sont lavé les mains.", en: "They washed their hands." },
    ],
    trap: "Write « Ils se sont parlé » without agreement because the construction is « parler à quelqu’un » and se is indirect.",
    exercise: {
      prompt: "Les lettres qu’elles se sont ___ étaient très longues.",
      options: ["envoyé", "envoyée", "envoyées"],
      answer: "envoyées",
      rationale: "« Les lettres » is the preceding feminine plural direct object; se means ‘to each other’ and is indirect.",
    },
    prerequisites: ["b1-past-participle-agreement", "b1-object-pronouns-y-en"],
    tags: ["pronominal verbs", "past participle", "agreement", "direct object", "indirect object"],
    sourceKeys: ["academie", "oqlf"],
    sourceNote: "Académie and OQLF descriptions support both parts of the analysis: the direct-object test for reflexive or reciprocal uses and normal subject agreement when se has no object function.",
  },
  {
    id: "b2-causative-faire-laisser",
    level: "B2",
    unit: "Agreement and causation",
    title: "Faire, laisser, and se faire + infinitive",
    summary: "Express causing, arranging, allowing, or undergoing an action.",
    objective: "Build a causative construction, keep fait invariable before an infinitive, and recognize both accepted treatments of laissé + infinitive.",
    rule: "Faire + infinitive means to cause or arrange an action; laisser + infinitive means to allow it. Object pronouns normally precede the conjugated causative verb. The past participle fait is always invariable when immediately followed by an infinitive. Before an infinitive, laissé may follow traditional agreement when a preceding direct object performs the infinitive, or remain invariable under the 1990 spelling reforms; both treatments are accepted.",
    pattern: "subject + faire/laisser + infinitive; fait stays invariable; laissé may follow the traditional rule or 1990 invariability",
    examples: [
      { fr: "Nous faisons réparer la chaudière.", en: "We are having the boiler repaired." },
      { fr: "Ils laissent les enfants choisir.", en: "They let the children choose." },
    ],
    trap: "Write « Elle s’est fait photographier », never « faite ». With laisser, accept both « Je les ai laissés partir » (traditional agreement) and « Je les ai laissé partir » (1990-reform invariability).",
    exercise: {
      prompt: "Elle s’est ___ couper les cheveux.",
      options: ["fait", "faite", "faits"],
      answer: "fait",
      rationale: "The past participle fait is invariable before an infinitive.",
    },
    prerequisites: ["b1-complement-prepositions", "b1-past-participle-agreement"],
    tags: ["causative", "faire", "laisser", "se faire", "past participle"],
    sourceKeys: ["academie", "oqlf"],
    sourceNote: "The invariant fait rule is normative. For laissé + infinitive, the lesson explicitly accepts both the traditional agreement where applicable and the blanket invariability introduced by the 1990 spelling reforms.",
  },
  {
    id: "b2-nonfinite-clauses",
    level: "B2",
    unit: "Condensed and formal style",
    title: "Past infinitives and participial clauses",
    summary: "Condense relationships of anteriority, cause, and circumstance.",
    objective: "Use a past infinitive or participial clause while maintaining a logically correct subject.",
    rule: "The past infinitive, avoir or être + past participle, presents an infinitive action as already completed. A participial clause can have an explicit subject and express cause, time, or circumstance. An unstated infinitive subject normally matches the controlling subject of the main clause.",
    pattern: "après + avoir/être + past participle; noun + present participle + main clause",
    examples: [
      { fr: "Après avoir terminé son travail, elle est sortie.", en: "After finishing her work, she went out." },
      {
        fr: "Les négociations ayant échoué, les deux parties ont quitté la salle.",
        en: "As the negotiations had failed, both parties left the room.",
      },
    ],
    trap: "Avoid dangling infinitives: in « Après avoir lu le dossier, la solution était évidente », the grammar makes « la solution » the reader.",
    exercise: {
      prompt: "Après ___ la porte, il est sorti.",
      options: ["fermer", "avoir fermé", "ayant fermé"],
      answer: "avoir fermé",
      rationale: "Closing was completed before leaving, so the past infinitive follows après.",
    },
    prerequisites: ["b1-gerondif-participe-present", "b1-plus-que-parfait"],
    tags: ["past infinitive", "participle clause", "anteriority", "formal style", "subject control"],
    sourceKeys: ["fei", "eduscol"],
    sourceNote: "These structures are presented as productive compression tools, with the subject-control constraint made explicit to prevent dangling clauses.",
  },
  {
    id: "b2-advanced-determiners-quantifiers",
    level: "B2",
    unit: "Condensed and formal style",
    title: "Advanced determiners and quantifiers",
    summary: "Control de, des, and agreement after complex quantity expressions.",
    objective: "Choose de or des in advanced noun phrases and make verbs agree with common quantifiers.",
    rule: "Quantity expressions normally take de: beaucoup de travail, peu d’erreurs. In careful usage, plural indefinite des generally becomes de before an adjective placed before its noun: de bonnes idées. La plupart des takes a plural verb, while chacun and aucun are normally singular.",
    pattern: "quantity + de + noun; des + preposed adjective + plural noun → usually de + adjective + noun",
    examples: [
      { fr: "La plupart des étudiants ont répondu.", en: "Most of the students replied." },
      { fr: "Elle a proposé de très bonnes solutions.", en: "She proposed some very good solutions." },
    ],
    trap: "The des-to-de change does not apply when the adjective follows the noun, and fixed compounds retain des: « des livres intéressants », « des petits pois ».",
    exercise: {
      prompt: "Which form is normally preferred in careful edited French? « Il a acheté ___ beaux livres d’histoire. »",
      options: ["des", "de", "du"],
      answer: "de",
      rationale: "Before the preposed plural adjective « beaux », careful edited French normally prefers de; des also occurs in accepted usage.",
    },
    prerequisites: ["a1-11", "a2-08"],
    tags: ["determiners", "quantifiers", "de", "des", "agreement"],
    sourceKeys: ["academie", "oqlf"],
    sourceNote: "The exercise explicitly targets the careful edited preference for de before most preposed plural adjectives; des remains an accepted variant in some usage, while fixed compounds retain des.",
  },
  {
    id: "b2-question-negation-register",
    level: "B2",
    unit: "Register and modality",
    title: "Formal questions and spoken versus written negation",
    summary: "Move accurately between conversational, neutral, and formal French.",
    objective: "Form formal inversion correctly and distinguish spoken negation from edited written French.",
    rule: "French can mark a question through intonation, est-ce que, or inversion. Formal complex inversion retains a noun subject and repeats it with a pronoun. Insert euphonic -t- between a vowel-ending verb and il, elle, or on when required. Spoken French often omits negative ne, but standard edited writing retains it.",
    pattern: "noun subject + verb-pronoun inversion; vowel-ending verb + -t-il/-t-elle/-t-on",
    examples: [
      { fr: "Quand arrivera-t-il ?", en: "When will he arrive?" },
      { fr: "Marie viendra-t-elle demain ?", en: "Will Marie come tomorrow?" },
    ],
    trap: "Use two hyphens around inserted t: « a-t-il ». Do not add it when the verb already ends in t or d: « vient-il », « prend-il ».",
    exercise: {
      prompt: "Which formal spelling is correct?",
      options: ["Paul a t’il compris ?", "Paul a-t-il compris ?", "Paul a-t’il compris ?"],
      answer: "Paul a-t-il compris ?",
      rationale: "Euphonic t is placed between two hyphens and takes no apostrophe.",
    },
    prerequisites: ["b1-indirect-speech-questions", "a2-09"],
    tags: ["questions", "inversion", "euphonic t", "negation", "register"],
    sourceKeys: ["cei", "fei", "academie"],
    sourceNote: "Register variation supports B2 sociolinguistic control; formal spelling follows normative guidance, while ne-omission is labeled as spoken rather than ‘incorrect French.’",
  },
  {
    id: "b2-modal-and-reported-conditional",
    level: "B2",
    unit: "Register and modality",
    title: "Modal nuance and the reported conditional",
    summary: "Distinguish obligation, inference, possibility, politeness, and unconfirmed reporting.",
    objective: "Infer a modal or conditional form’s meaning from its context rather than its form alone.",
    rule: "Devoir can express obligation or a strong inference; pouvoir can express permission or possibility. The conditional can soften advice or requests, present a future from a past viewpoint, or distance the speaker from unconfirmed information.",
    pattern: "devoir + infinitive → obligation or inference; reporting source + conditional → unconfirmed information",
    examples: [
      { fr: "Elle doit être chez elle : la lumière est allumée.", en: "She must be at home: the light is on." },
      {
        fr: "Selon la presse, le ministre démissionnerait.",
        en: "According to the press, the minister is reportedly going to resign.",
      },
    ],
    trap: "A conditional form does not have one automatic meaning. Decide from context whether it marks hypothesis, politeness, future-in-the-past, or reported uncertainty.",
    exercise: {
      prompt: "Choose the form that explicitly distances the speaker from the unconfirmed report: « Selon des informations non confirmées, l’accord ___ signé demain. »",
      options: ["sera", "serait", "soit"],
      answer: "serait",
      rationale: "The journalistic conditional explicitly distances the speaker from information that has not been confirmed; a future can be grammatical if the speaker adopts the report as their own assertion.",
    },
    prerequisites: ["b1-conditionnel-present", "b2-reported-speech-past"],
    tags: ["modality", "devoir", "pouvoir", "conditional", "reported information"],
    sourceKeys: ["cei", "fei", "academie"],
    sourceNote: "The lesson distinguishes several discourse meanings of the conditional and follows normative guidance on its distancing use in unconfirmed reports.",
  },
  {
    id: "b2-literary-past-recognition",
    level: "B2",
    unit: "Optional B2→C1 bridge",
    title: "Passé simple and passé antérieur — optional B2→C1 recognition bridge",
    summary: "Optionally recognize literary narrative tenses at B2 while deferring productive mastery to C1.",
    objective: "Recognize literary foreground events and events completed before them without producing these tenses at B2.",
    rule: "The passé simple normally presents foregrounded, completed events in literary narration. The passé antérieur uses passé simple forms of avoir or être plus a past participle and marks an event completed before another literary past event. This optional B2→C1 bridge is for recognition only; productive work is deferred to C1.",
    pattern: "passé antérieur event (earlier) → passé simple event (later)",
    examples: [
      { fr: "Il ouvrit la lettre et pâlit.", en: "He opened the letter and went pale." },
      { fr: "Dès qu’elle eut compris, elle partit.", en: "As soon as she had understood, she left." },
    ],
    trap: "Do not require learners to produce these tenses at B2 or in ordinary conversation, and do not mix them casually into a spoken narrative built with the passé composé.",
    exercise: {
      prompt: "In « Quand ils eurent fermé la porte, ils partirent », which action happened first?",
      options: ["They closed the door.", "They left.", "The actions were simultaneous."],
      answer: "They closed the door.",
      rationale: "« Eurent fermé » is the passé antérieur and marks the action completed before « partirent ».",
    },
    prerequisites: ["b1-past-narration", "b1-plus-que-parfait"],
    tags: ["passé simple", "passé antérieur", "literature", "reading", "recognition only", "optional B2→C1 bridge"],
    sourceKeys: ["fei", "eduscol", "academie"],
    sourceNote: "Optional B2→C1 recognition bridge: FEI places the passé simple in its C1 grammar inventory, so this course defers productive literary-past work to C1 and requires recognition only—not production—at B2.",
    recognitionOnly: true,
  },
];
